# -*- coding: utf-8 -*-
"""q2_library_system

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XQnGWgDW5f-gPdd69CrEMXfG5biFDuUf
"""

catalog = {}
borrowed_books = []
members = set()


def add_book(book_id, title, author, year):
    catalog[book_id] = (title, author, year)
    print("Book Added")

def borrow_book(book_id):
    if book_id in catalog:
        if book_id not in borrowed_books:
            borrowed_books.append(book_id)
            print("Book Borrowed")
        else:
            print("Book Already Borrowed")
    else:
        print("Book Not Found")
def return_book(book_id):
    if book_id in borrowed_books:
        borrowed_books.remove(book_id)
        print("Book Returned")
    else:
        print("Book Not Borrowed")

def register_member(member_id):
    members.add(member_id)
    print("Member Registered")
def show_available():
    print("\nAvailable Books:\n")
    for book_id in catalog:
        if book_id not in borrowed_books:
            print(book_id, catalog[book_id])


add_book(1, "Python", "John", 2020)
add_book(2, "AI Basics", "Smith", 2021)
add_book(3, "Machine Learning", "David", 2022)
add_book(4, "Data Science", "Alex", 2023)
print()
register_member(101)
register_member(102)
register_member(103)
register_member(101)
print()
borrow_book(1)
borrow_book(2)
print()
return_book(1)
print()
show_available()
print()
print("Members =", members)