# -*- coding: utf-8 -*-
"""q3_shopping_cart

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yc3TeQunrH5QG8zyLaWgk7Hv-xGIleCS
"""

print("PART A — Spot the Bug\n")

def add_item_bug(item, cart=[]):
    cart.append(item)
    return cart

print(add_item_bug("apple"))
print(add_item_bug("banana"))
print(add_item_bug("milk", cart=["bread"]))
print(add_item_bug("eggs"))

print("\nPART B — Fixed Version\n")

def add_item(item, cart=None):

    if cart is None:
        cart = []

    cart.append(item)
    return cart

print(add_item("apple"))
print(add_item("banana"))

print("\nPART C — Shopping Cart Program\n")

def create_cart(owner, discount=0):

    return {
        "owner": owner,
        "items": [],
        "discount": discount
    }

def add_to_cart(cart, name, price, qty=1):

    item = {
        "name": name,
        "price": price,
        "qty": qty
    }

    cart["items"].append(item)

def update_price(price_tuple, new_price):

    try:
        price_tuple[1] = new_price

    except TypeError as e:
        print("Tuple Error:", e)

def calculate_total(cart):

    total = 0

    for item in cart["items"]:

        total += item["price"] * item["qty"]

    discount_amount = total * (cart["discount"] / 100)

    final_total = total - discount_amount

    return final_total

cart1 = create_cart("Abhay", discount=10)
cart2 = create_cart("Riya", discount=5)

add_to_cart(cart1, "Apple", 50, 2)
add_to_cart(cart1, "Milk", 30, 1)

add_to_cart(cart2, "Bread", 40, 1)
add_to_cart(cart2, "Eggs", 10, 12)

print("Cart 1:")
print(cart1)

print("\nCart 2:")
print(cart2)

print("\nTotal for Cart 1:", calculate_total(cart1))
print("Total for Cart 2:", calculate_total(cart2))

print("\nTuple Immutability Demo:")

price_data = ("Laptop", 50000)

update_price(price_data, 55000)